os: osx
language: node_js

addons:
  homebrew:
    packages:
      - hugo

script:
  - hugo

deploy:
  provider: pages
  target-branch: master
  local-dir: public
  repo: Golubkov-P/golubkov-p.github.io
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
