language: node_js

install:
  - sudo apt-get update
  - sudo apt-get install hugo

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
