os: osx
language: node_js

addons:
  homebrew:
    packages:
      - hugo
    update: true

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  repo: golubkov-p.github.io
  on:
    branch: master
